name: commit-all-branches 
# trigger a commit message when pushed on any branch 
on: 
  push:
    branches:
      - master
      - production
      - test 

jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:  
      - name: print new_commit_done
        run: echo "New_comit"

      - name: "print current date"
        run: date   

